update github worflow

diff --git a/.github/workflows/preprod.yml b/.github/workflows/preprod.yml
--- a/.github/workflows/preprod.yml
+++ b/.github/workflows/preprod.yml
@@ -22,17 +22,12 @@ jobs:
         with:
           php-version: 8.2
           extensions: zip # Installation de l'extension ZIP
+          tools: composer # Assure que Composer est installé
           coverage: none
 
-      - name: Restore the Composer cache directory
-        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
-
-      - name: Cache Composer dependencies
-        uses: actions/cache@v3
-        with:
-          path: /tmp/composer-cache
-          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
-          restore-keys: ${{ runner.os }}-'8.0'-composer-
+      - name: Verify PHP Extensions
+        run: |
+          php -m | grep zip || echo "ext-zip is missing!"
 
       - name: Install dependencies
         uses: php-actions/composer@v6
@@ -70,8 +65,18 @@ jobs:
         uses: shivammathur/setup-php@v2
         with:
           php-version: 8.2
-          extensions: zip # Installation de l'extension ZIP
+          extensions: zip
+          tools: composer
           coverage: none
+
+      - name: Install required packages
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y php8.2-zip
+
+      - name: Verify PHP Extensions
+        run: |
+          php -m | grep zip || echo "ext-zip is missing!"
 
       - name: Download artifact
         uses: actions/download-artifact@v3
